@startuml
(*) --> "Заказ сделан"
 --> "передать заказ на кухню"

if "Гость заказал напиток" then
  -->[true] "Принести напиток сразу"
  --> "Принести еду по готовности"

else
  ->"Принести еду по готовности"
  -->[Ending process] (*)
@enduml