@startuml
!theme amiga
Guest -> Menu : chooses
Guest -> Waiter : makes the order
Waiter -> Kitchen : brings the order
activate Kitchen
Kitchen -> Kitchen : prepares oder
deactivate Kitchen
Kitchen -> Guest : gives ready meal back
activate Guest
Guest -> Guest : enjoys the meal
Guest -> Guest : ready to pay
Guest -> Waiter : pays for the meal
deactivate Guest
Waiter -> Guest : brings the receipt
@enduml





