@startuml
!theme hacker
state choice1 <<choice>>
state fork1   <<fork>>
state join2   <<join>>
state end3    <<end>>



[*]     --> choice1 :   человек проголодался
choice1 --> fork1   : выбрать готовую еду
choice1 --> Готовка   : приготовить себе еду
choice1 --> end3    : ничего не делатьи умереть

fork1   ---> ПойтиВЗаведение
fork1   --> ЗаказатьДоставку

ПойтиВЗаведение: 1. Собраться \n2. Добраться до заведения \n\t-Такси \n\t-Метро \n\t-Пешком
ЗаказатьДоставку: почти не требует усилий
ПойтиВЗаведение   --> join2
note left : человек сыт
Готовка: 1.Выбор блюда \n2.Готовка
Готовка --> join2
join2 -> [*]
@enduml


