@startuml
!theme cerulean
start
if (гость заказал напиток к еде?) then (no)
:передаем заказ на кухню;
fork
  :ждем пока сварится вермишель;
fork again
: готовим соус;
end fork
- смешиваем вермишель и соус
else (yes)
: Передаем заказ напитка на бар;
 endif
-забираем заказ с бара и кухни
-отдаем заказ гостю



stop
@enduml