@startuml

hide circle
entity "Офицант" as e01 {
  *имя
}

entity "Столик" as e02 {
 *номер
}

entity "Гость" as e03 {
 *имя
 ---
 *номер столика
}

entity "Заказ" as e04 {
 *номер столика
 ---
 *ответсвенный офицант
}

e01 ||..|{ e02
e02 ||..|{ e03
e01 ||..|{ e04
e03 ||..||e04

@enduml

