@startsalt
{

------
{T!
== Супы
== Название   | ==Обьем   |   ==Цена
+Борщ           |350 мл | 35
++Пампушки 4 штуки      | ....   | 5
+ Куриный суп   | 350 мл| 30
}
..
{T-
==Салаты
+Греческий салат  | 200гр | 40
+Цезар            | 200гр | 45
+С грибами        | 200гр | 35
}

..
== with T#
{T#
=Основные блюда
+ Название     | Вес    | Цена
+ Паста      | 300 грамм | 60
++ с беконом   | 320 грамм  | 65
++ с курицей   | 320 грамм | 65
}

}
@endsalt

